title: Gramps’ Pools
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  The best in pool construction
baseurl: "/pools-website" 
url: ""

# Build settings
markdown: kramdown

# plugins
plugins:

collections:
  - forums
  - currently

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  